name: Client Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  client-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ # Set the working directory to client folder

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # You can adjust this version as needed
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      
      - name: Install Dependencies
        run: npm ci # Using ci instead of install for cleaner, more reliable builds
      
      - name: Run Unit Tests
        run: npm test
        env:
          CI: true # Ensures tests run in CI mode
